### ISSUE TITLE
zero_ptr lint in constexpr contexts

### ISSUE THREAD

**Issue by aldanor** [Manishearth/rust-clippy#1606] opened 2017-03-06 00:51 UTC
As of the latest version, zero_ptr lint is triggered on invocations of `lazy_static!` macro which uses `0 as *const _` in a constexpr context where `ptr::null()` cannot be possibly used without a feature gate.

**Comment by oli-obk** [comment] 2017-03-06 07:28
Dupe of #1580

**Closed by oli-obk** 2017-03-06 07:28 UTC
