### ISSUE TITLE
Catch reverse ranges in for loops

### ISSUE THREAD

**Issue by Manishearth** [Manishearth/rust-clippy#110] opened 2015-07-11 20:55 UTC
```
fn main() {
   for i in (10..0) {
    println!("{}", i);
   } 
}
```

should be

```
fn main() {
   for i in (0..10).rev() {
    println!("{}", i);
   } 
}
```

https://github.com/rust-lang/rust/issues/26975

Might be a bit tricky to handle due to desugaring.

**Comment by llogiq** [comment] 2015-07-12 08:51
This is a duplicate of #96.

**Closed by llogiq** 2015-07-12 08:51 UTC
Labels: duplicate
