### ISSUE TITLE
Clippy does not output anything on Windows 10

### ISSUE THREAD

**Issue by CodeGradox** [Manishearth/rust-clippy#1453] opened 2017-01-19 18:39 UTC
When I run the command `cargo clippy` it does not output anything when run it in Powershell and CMD. However, when I run it in cmd.exe it shows a few Windows popup errors. There is no error output in the console window. Powershell runs without any error popups.

Running `cargo run` works fine and racer also works in Visual Studio Code. Running `cargo clippy` in Ubuntu for Windows (bash) works perfectly fine.

I don't know if it's an error on my side, but I can try to reinstall rustup and rust and see if that fixes it. I had the GNU toolchain installed. I'll try the msvc toolchains instead.
<hr>

Rustup: `1.0.0 (17b6d21 2016-12-15)`

Rust: `1.16.0-nightly (c8af93f09 2017-01-18)`

Cargo: `0.17.0-nightly (4d7b49b 2017-01-18)`

cargo install clippy --force shows `clippy v0.0.109`

```
cargo-clippy.exe - System Error
---------------------------
The program can't start because arena-30031a708a0da468.dll is missing from your computer. Try reinstalling the program to fix this problem. 
```

```
cargo-clippy.exe - System Error
---------------------------
The program can't start because rustc_errors-7b2165cc2a3752f6.dll is missing from your computer. Try reinstalling the program to fix this problem.
```

```
cargo-clippy.exe - System Error
---------------------------
The program can't start because std-1008ebd411f043f7.dll is missing from your computer. Try reinstalling the program to fix this problem.
```

```
cargo-clippy.exe - System Error
---------------------------
The program can't start because syntax_pos-337bfb4f3ecbfe90.dll is missing from your computer. Try reinstalling the program to fix this problem.
```

**Comment by CodeGradox** [comment] 2017-01-19 20:14
I did a fresh install of rustup with the msvc toolchain and reinstalled clippy and it still gives no output. cmd.exe still causes those error message dialogue boxes to appear.

**Comment by CodeGradox** [comment] 2017-01-19 20:17
I forgot to mention that adding clippy as an optional dependency and running `cargo build --features "clippy"` does work as intended.

**Comment by mzji** [comment] 2017-01-19 20:52
I have the same issue on my Win10 x64 box, didn't try to use clippy as a rustc plugin. rustc info:
```
rustc 1.16.0-nightly (c8af93f09 2017-01-18)
binary: rustc
commit-hash: c8af93f0901c336e873ce18274026d0fd9bc7c1f
commit-date: 2017-01-18
host: x86_64-pc-windows-msvc
release: 1.16.0-nightly
LLVM version: 3.9
```

**Comment by Manishearth** [comment] 2017-01-19 20:53
IIRC you have to set up PATH and LD_LIBRARY_PATH (or whatever the equivalent is) for this to work, this used to work with rustup but doesn't anymore

**Comment by mzji** [comment] 2017-01-19 20:54
I think this is a duplicate of #1422 .

**Closed** 2017-01-19 20:55 UTC
