### ISSUE TITLE
Can not find rustc plugin dll on windows

### ISSUE THREAD

**Issue by luyang177** [Manishearth/rust-clippy#1429] opened 2017-01-09 16:07 UTC
Run Cargo  clippy, and can not found rustc plugin dll, but my rust code works.
Clippy work fine on my ubuntu, but this is on windows, Windows always wast my time...

**Comment by Manishearth** [comment] 2017-01-09 16:10
Dupe of https://github.com/Manishearth/rust-clippy/issues/1422 . rustup is not setting the path right, setting LD_LIBRARY_PATH or PATH (forget which) to the folder where rustc_plugin is should work

**Closed by Manishearth** 2017-01-09 16:10 UTC
