### ISSUE TITLE
assert!(a == b, ...) to assert_eq!(a, b, ...)

### ISSUE THREAD

**Issue by ticki** [Manishearth/rust-clippy#1106] opened 2016-07-19 18:52 UTC
A warn-lint which detects equality assertions using `assert!` instead of `assert_eq!`. Generally, this is considered an anti-pattern.

**Comment by mcarton** [comment] 2016-07-19 19:31
I'd rather wait: there is some discussion about improving `assert!` itself (see https://github.com/rust-lang/rfcs/pull/1662 and https://github.com/rust-lang/rfcs/pull/1653).
Also note that currently `assert_eq!` requires its parameters to implement `Debug`, while `assert!(a == b)` does not.

**Comment by birkenfeld** [comment] 2016-08-05 16:03
Dupe of #641.

**Closed by birkenfeld** 2016-08-05 16:03 UTC
Labels: A-style, E-medium, L-lint, T-AST
