### ISSUE TITLE
Spot always false "else if" branches

### ISSUE THREAD

**Issue by leonardo-m** [Manishearth/rust-clippy#1596] opened 2017-03-03 19:16 UTC
I'd like Clippy to spot bugs like this, after the first test, the following tests are always false:

```
fn foo4(x: u32) -> u32 {
    if x > 20_000 { 0 }
    else if x > 100_000 { 1 }
    else if x > 200_000 { 2 }
    else { 3 }
}
```

**Comment by leonardo-m** [comment] 2017-03-03 19:20
A different example:

```
fn foo6(b: bool) -> u32 {
    if b {
        1
    } else if !b {
        2
    } else {
        3
    }
}
```

**Comment by mcarton** [comment] 2017-03-03 19:23
Duplicate of #1180.

**Closed by mcarton** 2017-03-03 19:23 UTC
