### ISSUE TITLE
False positive or_fun_call with Result

### ISSUE THREAD

**Issue by Riateche** [Manishearth/rust-clippy#1280] opened 2016-10-14 12:36 UTC
```
fn main() {
  let x: Result<String, ()> = Ok("asd".to_string());
  x.unwrap_or(String::new());
}
```

The message suggests `x.unwrap_or_default()` but there is no such method for `Result`. It exists only for `Option`.

**Comment by mcarton** [comment] 2016-10-14 12:38
Good catch!
See also https://github.com/rust-lang/rust/issues/37025.

**Comment by clarcharr** [comment] 2016-12-05 23:26
Actually: https://doc.rust-lang.org/nightly/std/result/enum.Result.html#method.unwrap_or_default

**Comment by llogiq** [comment] 2017-01-15 13:39
I'm closing this as it seems to be working as designed. Please reopen if you disagree.

**Closed by llogiq** 2017-01-15 13:39 UTC
Labels: L-bug
