### ISSUE TITLE
Clippy does not compile using rustc 1.18.0-nightly

### ISSUE THREAD

**Issue by polybuildr** [Manishearth/rust-clippy#1656] opened 2017-04-02 12:44 UTC
```
$ rustup show

Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.18.0-nightly (5e122f59b 2017-04-01)

$ cargo install clippy

... errors

error: aborting due to 37 previous errors

error: Could not compile `clippy_lints`.
Build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.121`, intermediate artifacts can be found at `/tmp/cargo-install.QwQuJkJrXTUK`
```

Am I missing something or is this a bug in clippy?

**Comment by mcarton** [comment] 2017-04-02 13:03
Dupe of  #1646.

**Closed by mcarton** 2017-04-02 13:03 UTC
