### ISSUE TITLE
False positive for map_clone

### ISSUE THREAD

**Issue by malbarbo** [Manishearth/rust-clippy#1496] opened 2017-01-30 19:36 UTC
```
pub fn g<I: IntoIterator<Item = u32>>(_: I) {}

pub fn f() {
    let mut v = vec![1u32, 2, 3];

    let iter = v.iter_mut();

    g(iter.map(|x| *x)); // suggests iter.cloned(), but it does not compile
}
```

**Comment by mcarton** [comment] 2017-01-30 19:40
Dupe of #443?

**Comment by malbarbo** [comment] 2017-01-30 19:42
Ops.. My bad.

**Closed** 2017-01-30 19:42 UTC
