### ISSUE TITLE
Can't install Clippy on the latest nightly rustc

### ISSUE THREAD

**Issue by BookOwl** [Manishearth/rust-clippy#1650] opened 2017-03-31 21:04 UTC
I just updated to the latest Rust and tried to reinstall clippy. I got these errors:

```
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing clippy v0.0.121
   Compiling num-traits v0.1.37
   Compiling matches v0.1.4
   Compiling semver-parser v0.7.0
   Compiling serde v0.9.12
   Compiling itoa v0.3.1
   Compiling quine-mc_cluskey v0.2.4
   Compiling dtoa v0.4.1
   Compiling rustc-serialize v0.3.23
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling regex-syntax v0.4.0
   Compiling unicode-normalization v0.1.4
   Compiling semver v0.6.0
   Compiling serde_json v0.9.9
   Compiling synom v0.11.3
   Compiling toml v0.2.1
   Compiling syn v0.11.9
   Compiling clippy_lints v0.0.121
error[E0432]: unresolved import `syntax::codemap::mk_sp`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/formatting.rs:2:5
  |
2 | use syntax::codemap::mk_sp;
  |     ^^^^^^^^^^^^^^^^^^^^^^ no `mk_sp` in `codemap`

error[E0432]: unresolved import `syntax::codemap::mk_sp`
 --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/swap.rs:4:5
  |
4 | use syntax::codemap::mk_sp;
  |     ^^^^^^^^^^^^^^^^^^^^^^ no `mk_sp` in `codemap`

error[E0425]: cannot find function `mk_sp` in module `codemap`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/let_if_seq.rs:75:37
   |
75 |                 let span = codemap::mk_sp(stmt.span.lo, if_.span.hi);
   |                                     ^^^^^ not found in `codemap`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/consts.rs:248:80
    |
248 |             ExprIf(ref cond, ref then, ref otherwise) => self.ifthenelse(cond, then, otherwise),
    |                                                                                ^^^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
    |
    = note: expected type `&rustc::hir::Block`
               found type `&syntax::ptr::P<rustc::hir::Expr>`
    = help: here are some functions which might fulfill your needs:
            - .unwrap()

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:100:9
    |
100 |     rhs.expn_id != lhs.expn_id
    |         ^^^^^^^ did you mean `hi`?

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:100:24
    |
100 |     rhs.expn_id != lhs.expn_id
    |                        ^^^^^^^ did you mean `hi`?

error: no method named `with_expn_info` found for type `&syntax::codemap::CodeMap` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:115:25
    |
115 |     cx.sess().codemap().with_expn_info(span.expn_id, |info| {
    |                         ^^^^^^^^^^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:115:45
    |
115 |     cx.sess().codemap().with_expn_info(span.expn_id, |info| {
    |                                             ^^^^^^^ did you mean `hi`?

error: no method named `with_expn_info` found for type `&syntax::codemap::CodeMap` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:149:25
    |
149 |     cx.sess().codemap().with_expn_info(span.expn_id, |info| in_macro_ext(cx, info))
    |                         ^^^^^^^^^^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:149:45
    |
149 |     cx.sess().codemap().with_expn_info(span.expn_id, |info| in_macro_ext(cx, info))
    |                                             ^^^^^^^ did you mean `hi`?

error: no method named `with_expn_info` found for type `&syntax::codemap::CodeMap` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:701:14
    |
701 |             .with_expn_info(span.expn_id, |expn| expn.map(|ei| (ei.callee.name(), ei.call_site)));
    |              ^^^^^^^^^^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:701:34
    |
701 |             .with_expn_info(span.expn_id, |expn| expn.map(|ei| (ei.callee.name(), ei.call_site)));
    |                                  ^^^^^^^ did you mean `hi`?

error: no method named `with_expn_info` found for type `&syntax::codemap::CodeMap` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:722:10
    |
722 |         .with_expn_info(span.expn_id, |expn| expn.map(|ei| (ei.callee.name(), ei.call_site)));
    |          ^^^^^^^^^^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/mod.rs:722:30
    |
722 |         .with_expn_info(span.expn_id, |expn| expn.map(|ei| (ei.callee.name(), ei.call_site)));
    |                              ^^^^^^^ did you mean `hi`?

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/hir.rs:100:55
    |
100 |                 self.eq_expr(lc, rc) && self.eq_block(lt, rt) && both(le, re, |l, r| self.eq_expr(l, r))
    |                                                       ^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
    |
    = note: expected type `&rustc::hir::Block`
               found type `&syntax::ptr::P<rustc::hir::Expr>`
    = help: here are some functions which might fulfill your needs:
            - .unwrap()

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/hir.rs:100:59
    |
100 |                 self.eq_expr(lc, rc) && self.eq_block(lt, rt) && both(le, re, |l, r| self.eq_expr(l, r))
    |                                                           ^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
    |
    = note: expected type `&rustc::hir::Block`
               found type `&syntax::ptr::P<rustc::hir::Expr>`
    = help: here are some functions which might fulfill your needs:
            - .unwrap()

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/hir.rs:398:33
    |
398 |                 self.hash_block(t);
    |                                 ^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
    |
    = note: expected type `&rustc::hir::Block`
               found type `&syntax::ptr::P<rustc::hir::Expr>`
    = help: here are some functions which might fulfill your needs:
            - .unwrap()

error: no method named `source_callsite` found for type `&syntax::codemap::CodeMap` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/utils/internal_lints.rs:131:49
    |
131 |             let lint_span = cx.sess().codemap().source_callsite(lint_span);
    |                                                 ^^^^^^^^^^^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/collapsible_if.rs:128:22
    |
128 |         if expr.span.expn_id != inner.span.expn_id {
    |                      ^^^^^^^ did you mean `hi`?

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/collapsible_if.rs:128:44
    |
128 |         if expr.span.expn_id != inner.span.expn_id {
    |                                            ^^^^^^^ did you mean `hi`?

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/copies.rs:242:25
    |
242 |             blocks.push(&**block);
    |                         ^^^^^^^^ expected struct `rustc::hir::Expr`, found struct `rustc::hir::Block`
    |
    = note: expected type `&rustc::hir::Expr`
               found type `&rustc::hir::Block`

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/copies.rs:246:13
    |
246 |     (conds, blocks)
    |             ^^^^^^ expected struct `rustc::hir::Block`, found struct `rustc::hir::Expr`
    |
    = note: expected type `rustc_data_structures::small_vec::SmallVec<[&rustc::hir::Block; 1]>`
               found type `rustc_data_structures::small_vec::SmallVec<[&rustc::hir::Expr; 1]>`

error: no field `expr` on type `&syntax::ptr::P<rustc::hir::Expr>`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/entry.rs:50:50
   |
50 |                                     ((then_block.expr.is_some() as usize) + then_block.stmts.len() == 1);
   |                                                  ^^^^

error: no field `stmts` on type `&syntax::ptr::P<rustc::hir::Expr>`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/entry.rs:50:88
   |
50 |                                     ((then_block.expr.is_some() as usize) + then_block.stmts.len() == 1);
   |                                                                                        ^^^^^

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/entry.rs:61:46
   |
61 |                     walk_block(&mut visitor, then_block);
   |                                              ^^^^^^^^^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
   |
   = note: expected type `&rustc::hir::Block`
              found type `&syntax::ptr::P<rustc::hir::Expr>`
   = help: here are some functions which might fulfill your needs:
           - .unwrap()

error[E0560]: struct `syntax_pos::Span` has no field named `expn_id`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/if_let_redundant_pattern_matching.rs:78:25
   |
78 |                         expn_id: expr.span.expn_id,
   |                         ^^^^^^^^ field does not exist - did you mean `ctxt`?

error: no field `expn_id` on type `syntax_pos::Span`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/if_let_redundant_pattern_matching.rs:78:44
   |
78 |                         expn_id: expr.span.expn_id,
   |                                            ^^^^^^^ did you mean `hi`?

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/let_if_seq.rs:72:60
   |
72 |                 let Some(value) = check_assign(cx, def_id, then),
   |                                                            ^^^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
   |
   = note: expected type `&rustc::hir::Block`
              found type `&syntax::ptr::P<rustc::hir::Expr>`
   = help: here are some functions which might fulfill your needs:
           - .unwrap()

error: no field `stmts` on type `&syntax::ptr::P<rustc::hir::Expr>`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/let_if_seq.rs:108:34
    |
108 |                     then=if then.stmts.len() > 1 { " ..;" } else { "" },
    |                                  ^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/methods.rs:1068:42
     |
1068 |         let same_span = map_args[1].span.expn_id == unwrap_args[1].span.expn_id;
     |                                          ^^^^^^^ did you mean `hi`?

error: no field `expn_id` on type `syntax_pos::Span`
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/methods.rs:1068:73
     |
1068 |         let same_span = map_args[1].span.expn_id == unwrap_args[1].span.expn_id;
     |                                                                         ^^^^^^^ did you mean `hi`?

error: no field `expn_id` on type `syntax_pos::Span`
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/methods.rs:1097:42
     |
1097 |         let same_span = map_args[1].span.expn_id == unwrap_args[1].span.expn_id;
     |                                          ^^^^^^^ did you mean `hi`?

error: no field `expn_id` on type `syntax_pos::Span`
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/methods.rs:1097:73
     |
1097 |         let same_span = map_args[1].span.expn_id == unwrap_args[1].span.expn_id;
     |                                                                         ^^^^^^^ did you mean `hi`?

error: no method named `with_expn_info` found for type `&syntax::codemap::CodeMap` in the current scope
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/misc.rs:502:25
    |
502 |     cx.sess().codemap().with_expn_info(expr.span.expn_id, |info_opt| {
    |                         ^^^^^^^^^^^^^^

error: no field `expn_id` on type `syntax_pos::Span`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/misc.rs:502:50
    |
502 |     cx.sess().codemap().with_expn_info(expr.span.expn_id, |info_opt| {
    |                                                  ^^^^^^^ did you mean `hi`?

error[E0308]: mismatched types
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/needless_bool.rs:79:37
   |
79 |             match (fetch_bool_block(then_block), fetch_bool_expr(else_expr)) {
   |                                     ^^^^^^^^^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
   |
   = note: expected type `&rustc::hir::Block`
              found type `&syntax::ptr::P<rustc::hir::Expr>`
   = help: here are some functions which might fulfill your needs:
           - .unwrap()

error[E0308]: mismatched types
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/shadow.rs:308:29
    |
308 |             check_block(cx, then, bindings);
    |                             ^^^^ expected struct `rustc::hir::Block`, found struct `syntax::ptr::P`
    |
    = note: expected type `&rustc::hir::Block`
               found type `&syntax::ptr::P<rustc::hir::Expr>`
    = help: here are some functions which might fulfill your needs:
            - .unwrap()

error: no method named `source_callsite` found for type `&syntax::codemap::CodeMap` in the current scope
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/vec.rs:53:44
   |
53 |             let span = cx.sess().codemap().source_callsite(arg.span);
   |                                            ^^^^^^^^^^^^^^^

error[E0560]: struct `syntax_pos::Span` has no field named `expn_id`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/vec.rs:73:21
   |
73 |                     expn_id: args[0].span.expn_id,
   |                     ^^^^^^^^ field does not exist - did you mean `ctxt`?

error: no field `expn_id` on type `syntax_pos::Span`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.121/src/vec.rs:73:43
   |
73 |                     expn_id: args[0].span.expn_id,
   |                                           ^^^^^^^ did you mean `hi`?

error: aborting due to 37 previous errors

error: Could not compile `clippy_lints`.
Build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.121`, intermediate artifacts can be found at `/var/folders/tz/4tyj25lx1w3gm6bz3d4wbwx00000gn/T/cargo-install.8xpWiLYFWBBq`

Caused by:
  build failed
```
I'm using rustc 1.18.0-nightly (5c94997b6 2017-03-30)

**Comment by oli-obk** [comment] 2017-03-31 21:11
Dupe of #1646

**Closed by oli-obk** 2017-03-31 21:11 UTC
