### ISSUE TITLE
Warn about needless cast to *mut from &mut

### ISSUE THREAD

**Issue by fuine** [Manishearth/rust-clippy#1333] opened 2016-11-08 20:52 UTC
Consider this code:
```
fn foo<T>(_: *mut T) {}

fn main() {
    let mut x = 6;
    foo(&mut x as *mut _);
}
```
`foo` call can as well be written as `foo(&mut x);`, as the reference implicitly coerces to `*mut`. Clippy should warn about this unneeded cast.

**Comment by oli-obk** [comment] 2016-11-08 21:31
dupe of #1027 

I'll add your example to it

**Closed** 2016-11-08 21:32 UTC
