### ISSUE TITLE
`or_fun_call` should ignore `const fn`s

### ISSUE THREAD

**Issue by sgrif** [Manishearth/rust-clippy#1527] opened 2017-02-10 12:50 UTC
Hi there. I was surprised to find that clippy warns on `foo.map(CStr::as_ptr).unwrap_or(ptr::null_mut())`. Given that `null_mut` is a `const fn`, forcing it to be in `unwrap_or_else(|| ptr::null_mut())` is just noise. (I'm also unsure whether enum constructors are technically `const fn`s, but fixing this could potentially fix #1338)

**Comment by mcarton** [comment] 2017-02-12 17:27
I cannot reproduce even in diesel's repo and this should have been fixed in #917. The original PR on diesel is older than #917, this might have been the problem.
I can however reproduce #1338.
Feel free to reopen if you have a reproducible example.

**Closed by mcarton** 2017-02-12 17:27 UTC
Labels: E-medium, L-bug, T-middle

**Comment by killercup** [comment] 2017-02-12 18:34
> The original PR on diesel is older than #917, this might have been the problem.

Can confirm. I'm pretty good at cargo culting changes like that without thinking about it 😄
