### ISSUE TITLE
Clippy thinks Serialize is ineffective

### ISSUE THREAD

**Issue by CryZe** [Manishearth/rust-clippy#1886] opened 2017-07-12 15:28 UTC
```rust
extern crate serde;
#[macro_use]
extern crate serde_derive;

#[derive(Serialize, Deserialize)]
struct Test {
   a: u32,
   b: bool,
}
```
[Playground Link (just click the clippy button)](https://play.rust-lang.org/?gist=fd1f660c6344a4612a798c0fd2f91ffb&version=stable)

```
 Compiling playground v0.0.1 (file:///playground)
warning: the operation is ineffective. Consider reducing it to `Serialize`
 --> src/main.rs:5:10
  |
5 | #[derive(Serialize, Deserialize)]
  |          ^^^^^^^^^
  |
  = note: #[warn(identity_op)] on by default
  = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#identity_op

    Finished dev [unoptimized + debuginfo] target(s) in 0.67 secs
```

**Comment by kennytm** [comment] 2017-07-12 16:11
Duplicate of #1877.

**Closed** 2017-07-12 16:25 UTC
