### ISSUE TITLE
Shared Library Issue on latest Nightly

### ISSUE THREAD

**Issue by CryZe** [Manishearth/rust-clippy#964] opened 2016-05-28 17:19 UTC
I just compiled the latest clippy on the latest nightly and I'm getting this error:
```
C:/Users/Christopher/.cargo/bin/cargo-clippy.exe: error while loading shared libraries: rustc_driver-cb705824.dll: cannot open shared object file: No such file or directory
```

rustc 1.10.0-nightly (7bddce693 2016-05-27)
clippy 0.0.70
rustup 0.1.12 (c6e430a 2016-05-12)

**Comment by mcarton** [comment] 2016-05-28 18:05
Duplicate of #923. Looks to have been fixed in https://github.com/rust-lang-nursery/rustup.rs/pull/402 but no new version of *rustup* have been published yet.

**Closed by mcarton** 2016-05-28 18:05 UTC

**Comment by xetra11** [comment] 2016-09-22 14:22
Have a similar error:

mentioned file in error: `librustc_driver-8102329f.so`

**Comment by mcarton** [comment] 2016-09-22 14:24
@xetra11 could you provide a full log, versions of rustc, rustup & clippy and OS?

**Comment by xetra11** [comment] 2016-09-22 17:44
sure sorry...

OS: Linux Mint
rustc 1.13.0-nightly (c772948b6 2016-09-20)
rustup 0.6.3 (a0e2132 2016-08-28)
clippy throws this error (no version possible): `/home/xetra11/.cargo/bin/cargo-clippy: error while loading shared libraries: librustc_driver-8102e29f.so: cannot open shared object file: No such file or directory
`

**Comment by mcarton** [comment] 2016-09-22 21:19
Are you using `cargo clippy` or `cargo-clippy`?
The later needs `./.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib` in your path.

**Comment by xetra11** [comment] 2016-09-23 10:49
Both commands execute "cargo-clippy" and therefore its the same error message for both
