### ISSUE TITLE
New Lint: Do not comment out code

### ISSUE THREAD

**Issue by Evrey** [Manishearth/rust-clippy#1677] opened 2017-04-15 14:15 UTC
Based on [this HIC++ guideline](http://www.codingstandard.com/rule/2-3-2-do-not-comment-out-code/). We could check this by trying to parse comments as source code. As parsing all the comments would be a ridiculous amount of work, I suggest doing a string search on comments first, which will look for typical *"code-y stuff"* like `::`, `f32`, `->`, and what not. Might fail faster than parsing, but might as well be way slower.

Anyways, this lint should remember the programmer of the existence and purpose of VCS, especially if the crate is set up to use Git or whatever. Perhaps with a short example on how to revert the last commit using the crate's VCS.

**Comment by mcarton** [comment] 2017-04-15 15:49
Note that clippy does no see regular comments as they are not present is the AST.

**Comment by Evrey** [comment] 2017-04-15 16:14
`E-hard` indeed, then, which might put this suggestion somewhere on the edge of *"worth it?"*.

**Comment by marcelbuesing** [comment] 2017-06-14 19:55
Duplicate of #1348

**Comment by mcarton** [comment] 2017-06-14 22:09
Indeed, thanks for cleanup!

**Closed by mcarton** 2017-06-14 22:09 UTC
Labels: E-hard, L-lint, T-AST
